### ISSUE TITLE
Handle missing min/max gracefully for sliders/scrollbars

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-ui-swing#32]
Currently, the UI hangs when trying to use a numeric parameter with `style=slider`, but `min` or `max` undefined:

```groovy
#@ int (style=slider) a
```

This should be handled gracefully, by checking for `softMin != null` and `softMax != null` here:

https://github.com/scijava/scijava-ui-swing/blob/221d3c64690eae2f9fd440a90337fc367aaae36e/src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java#L102-L124

If no slider or scroll bar can be rendered, we should fallback to the standard textfield/spinner combination and log a warning message.

**Comment by ctrueden** [comment]
I did some digging. The reason it freezes is not because min and max are null—that would throw an NPE after all. It's because min defaults to `Integer.MIN_VALUE` and max to `Integer.MAX_VALUE`. The UI builder then proceeds to try to make a slider or scroll bar with a massively huge range, and the CPU goes to 100% indefinitely. The problem is [this](https://github.com/scijava/scijava-common/blob/scijava-common-2.66.1/src/main/java/org/scijava/widget/DefaultWidgetModel.java#L199) and [that](https://github.com/scijava/scijava-common/blob/scijava-common-2.66.1/src/main/java/org/scijava/widget/DefaultWidgetModel.java#L206) lines of code in the `DefaultWidgetModel`.

A possible fix would be to change the code that creates the `JScrollBar` or `JSlider` to be more conservative about what it feeds to those constructors. This would also guard against the case of explicit `min="-1000000000", max="1000000000"` sorts of inputs.

**Comment by imagejan** [comment]
Thanks for digging, @ctrueden!
I think we can tackle this at the same time as allowing non-integer step sizes in sliders (see https://github.com/scijava/scijava-ui-swing/issues/31), by adjusting the step size in case the number of possible steps gets unreasonably high (the acceptable limit might have to be found by testing with different settings).

**Comment by ctrueden** [comment]
I believe I have fixed the integer cases. Handling non-integers will be more involved, though.
