### ISSUE TITLE
Improve scroll behavior in Swing input dialog

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-ui-swing#74]
See [this topic](https://forum.image.sc/t/script-parameters-scrollable-gui-cursor-jumps/64965?u=imagejan) on the forum.

/cc @pr4deepr @bvandenbroek

**Comment by tferr** [comment]
This could be platform specific. I don't seem to reproduce this on Ubuntu 22.04 (with the default zulu8.60.0.21-ca-fx-jdk8.0.322 JDK). At this point would be useful to know which platforms are affected.

**Comment by pr4deepr** [comment]
I've tried it on Windows 10 and on a Mac (think it was Big Sur). 

Cheers
Pradeep

**Comment by bvandenbroek** [comment]
Hi guys,
Any news on this topic? I see the jumping-to-the-middle behavior on _all_ Windows 10 machines.
It only happens with long dialogs, maybe that's why @tferr couldn't reproduce it?
Sorry to nag, but it's really quite annoying.

Thanks!
Bram

**Comment by tferr** [comment]
I can reproduce this indeed. Not sure why I was not able to reproduce it before. I executed the snippet from the forum post and the jump occurs when I click on a checkbox or a JSpinner. The window does not be particularly tall, just it needs to be resized so that the vertical scrollbar appears.

Unbearable indeed. Makes it impossible to use the prompt. Unfortunately, I don't know really where to look.

**Comment by bvandenbroek** [comment]
Hi, it's been a while since @tferr 's last message. The issue still remains. Where should we take it so it can be solved? Should it perhaps be posted at https://github.com/scijava/scijava-ui-swing/issues?

Best regards,
Bram

**Comment by ctrueden** [comment]
@bvandenbroek wrote:
> Where should we take it so it can be solved? Should it perhaps be posted at https://github.com/scijava/scijava-ui-swing/issues?

This is already a scijava-ui-swing issue. You write in the passive voice "so it can be solved"—but the real first question is *who* will do the solving? This issue has been open for two years, with multiple people able to reproduce and complaining about it being "unbearable" and yet no one has tried to fix it. So how "unbearable" is it, really? Not unbearable enough for those affected to investigate any further, it seems.

Anyway, it was a bug relating to HTML message parameters. I fixed it. Run _Help &rarr; Update..._ to receive the fix. I hope Fiji is a little less unbearable now. :smile_cat:

**Comment by pr4deepr** [comment]
Thanks a lot @ctrueden . Appreciate it!

**Comment by bvandenbroek** [comment]
Hi @ctrueden,

First: thanks for fixing this!

Second: I wrote in the passive voice because my skills don't go much beyond reporting and testing in this case. Because the last message was posted more than a year ago, Tiago saying that he didn't know where to look to debug it, and nobody else picked it up, I thought that maybe it was a Java bug outside the Fiji realm. So I meant "where should I report the issue so that the right people see it and can solve it."
Sorry if that has annoyed you. I'm super grateful for all the great tools you guys create and maintain.

By the way, I never said it was unbearable. I did say 'quite annoying'. What's more, the researchers I make the scripts for simply observe the scrolling error, shrug and think "Ok, we live with it". But I'm happy that it is fixed now, and the silent masses will also, but you just don't hear from them. 😊

**Comment by ctrueden** [comment]
@bvandenbroek Sorry for being cranky yesterday. Sometimes the crush of thousands of open issues gets to me, and it's easy to feel like "why am I the only person in the world able to work on this? The code is *right there*!" But I fully appreciate that what takes me an hour to fix might be unapproachable for a non-programmer.

On the flip side, it's easy for any of us to fall into the trap of thinking "whoever could fix this fastest should always be the one to do it"—but it's not feasible mathematically: if I did nothing but attack every issue in Fiji's backlog of 3525 items, full time with perfect efficiency, and each item took only 1 hour to fix, it would still take me almost 2 years. :sweat: It's simply not possible; all I can do is occasionally attack the issues that seem most impactful, part of which is measured by people following up. So thank you for the ping pushing me to investigate—I appreciate it, despite the crankiness.
