### ISSUE TITLE
Spinners are missing up/down arrows with FlatLaf

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-ui-swing#77]
As [reported on the Image.sc Forum](https://forum.image.sc/t/missing-spinner-buttons-with-flatlaf-look-and-feel/72185):

> Unfortunately, spinner buttons in ImageJ2 style ContextCommand plugins are missing. Other L&Fs work.

To reproduce:
* From the Script Editor, choose _Templates &rarr; Intro &rarr; Widgets (JavaScript)_.
* Delete the `BigInteger` and `BigDecimal` parameters (there's currently a bug affecting them)
* When the dialog box appears, observe that none of the numeric parameters have spinner arrows, only text fields

**Comment by DevCharly** [comment]
Following lines cause the problem:

https://github.com/scijava/scijava-ui-swing/blob/40bd474d8b9b169d521a621ddf9772a718ce6e26/src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java#L131-L133

`spinner.getSize()` always returns `0, 0` because the spinner was just created and is not yet layouted.
So the preferred height of the spinner becomes `0`, which FlatLaf does not like.
Probably a bug in FlatLaf. Will investigate...

Anyway seems that the intention of the above code is to limit the preferred width of the spinner.
Replacing `spinner.getSize()` with `spinner.getPreferredSize()` should fix the issue.

**Comment by imagejan** [comment]
Thanks for the suggestion, @DevCharly. I can confirm this fixes the issue, and opened #78.

**Comment by tferr** [comment]
FYI, I actually don't think (I could be, of course, wrong - I did not test any other L&F)  limiting the preferred width of the spinner is needed. Things seem to work fine if one leaves it to defaults. Maybe this is just some historic code that has been carried over!? On #79, I have a couple of proposals on things that I found when looking into this.

**Comment by tferr** [comment]
> FYI, I actually don't think (I could be, of course, wrong - I did not test any other L&F)  limiting the preferred width of the spinner is needed. Things seem to work fine if one leaves it to defaults

I was wrong of course. The rationale for this is explained here: https://github.com/scijava/scijava-ui-swing/pull/79#issuecomment-1264787285
